inc20 - https
alekseyzharkov/shortr pull request #11
Opened 2022-12-18 12:03 UTC by alekseyzharkov

2022-12-22 18:51 UTC, kilchik requested changes

2022-12-22 18:51 UTC, kilchik commented on cmd/shortener/main.go
> +	signal.Notify(sigint, os.Interrupt)
А как же SIGTERM и SIGQUIT?

2022-12-22 18:51 UTC, kilchik commented on cmd/shortener/main.go
> +		if err := server.Shutdown(); err != nil {
Ты забыл про горутину, которая удаляет урлы. Если пользователь завершит работу сервиса, а перед самым Shutdown придет запрос на DeleteUserURLs, то нет гарантий, что программа завершится после успешного запроса на удаление, возможно она завершится до его начала, это в свою очередь приведет к неконсистентности данных. Этот момент нужно доработать для настоящего graceful shutdown

2022-12-26 10:00 UTC, alekseyzharkov commented on cmd/shortener/main.go
> +		if err := server.Shutdown(); err != nil {
исправления вынес от отдельный коммит

2022-12-26 16:47 UTC, kilchik requested changes

2022-12-26 16:47 UTC, kilchik commented on internal/app/controllers/delete_user_urls.go
> +	d := <-c.deleteInfoChannel
Тут что-то явно не так. Попробуй выполнить несколько запросов на delete подряд, я вижу, что отработает только первый
Кроме того Deleter ведь никак не получает информацию о завершении приложения

2022-12-28 08:19 UTC, alekseyzharkov commented on internal/app/controllers/delete_user_urls.go
> +	d := <-c.deleteInfoChannel
проверил с запросами, исправил как смог, наверное не очень красиво, но лучше пока не умею :/
Deleter не получает информацию, но main ждёт его завершения по каналу, как я понимаю
``<-controller.DeleteDone``

2022-12-28 08:21 UTC, alekseyzharkov commented on internal/app/controllers/delete_user_urls.go
> +	d := <-c.deleteInfoChannel
исправления отдельным коммитом

2022-12-29 20:22 UTC, kilchik commented on internal/app/controllers/delete_user_urls.go
>  func (c Controller) Deleter() {
Но ведь чтобы Deleter знал про сигнал ОС тебе достаточно ему передать ctx из главной горутины, а далее в цикле
```
for {
  select {
  case <-ctx.Done():
    close(done)
    return
  default:
     c.storage.Delete(d.tokens, d.authUser)
}
```

2022-12-29 20:23 UTC, kilchik approved these changes

2023-01-09 07:34 UTC, merged